### ISSUE TITLE
Consider adding a "status compressed/full" flag to AgentToServer

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opamp-spec#109]
The Server currently cannot tell if the status was compressed. As a consequence when it receives a message from an Agent it didn't see before it needs to ask for the full status. This unnecessary extra exchange when the Agent reports to the Server for the first time.
This can be avoided if we add a bit flag to indicate the that the status was compressed. If it is not (as is the case for newly starting Agents) the Server won't ask for full status.

**Comment by tigrannajaryan** [comment]
Here is a draft implementation with the new flag: https://github.com/open-telemetry/opamp-go/pull/103

**Comment by andykellr** [comment]
BindPlane OP does not currently support AgentHealth (coming soon!), but for RemoteConfigStatus I check `AgentCapabilities_AcceptsRemoteConfig`. I figured that if it accepts remote config then it should support reporting status.

For AgentHeath we could add `AgentCapabilities_ReportsAgentHealth`.

**Comment by tigrannajaryan** [comment]
@andykellr he is another draft PR that implements the approach you suggested: https://github.com/open-telemetry/opamp-go/pull/105

It is a smaller change, but I am reluctant with this approach since it requires more checks to detect compression, which is a potential source of bug.

Thoughts?

**Comment by andykellr** [comment]
I don't feel that strongly about it, but in general my instinct is to avoid a second piece of information that can already be derived from the information that exists. Typically this leads to ambiguity when the flag says it is complete (but it isn't) or the flag says it is not complete (but it is).

In this particular case, as long as we consider the flag authoritative, I don't see an issue. This means that if the flag says it is complete, ReportFullState should not report additional information and if the flag says it is incomplete, ReportFullState should report additional information. It does simplify reasoning about the message.

**Comment by tigrannajaryan** [comment]
@andykellr I thought a bit more and I agree with you. Closing this in favour of https://github.com/open-telemetry/opamp-spec/pull/111 and https://github.com/open-telemetry/opamp-go/pull/105
