### ISSUE TITLE
Consider adding a header for WebSocket messages to allow future extensibility

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opamp-spec#133]
## Problem

The WebSocket messages currently are serialized Protobuf AgentToServer/ServerToAgent messages. While Protobuf allows to easily add new fields to AgentToServer/ServerToAgent messages, there is no easy way to make any changes to how the Protobuf messages are serialized and stored in WebSocket messages. We will be essentially locked into this design decision.

## Proposed Solution

I would like to consider adding a simple extensibility mechanism to this part of the protocol - a one-byte header for WebSocket messages. Every WebSocket message is composed of 2 parts: one-byte header, followed by the serialized Protobuf AgentToServer/ServerToAgent messages. 

The current value of the one-byte header is equal to 0. In the future when non-zero values of headers are introduced their use should be negotiated during the connection phase (via HTTP headers or via Capabilities fields). This is necessary to ensure interoperability between different OpAMP versions. Non-zero header values will not be a breaking change, they will only used after successful negotiation between the Client and Server.

Note: we don't need the one-byte header for plain HTTP transport. Any extensibility for HTTP can be done via HTTP headers (not suitable for WebSocket since it cannot work per message - HTTP headers are sent once per connection).

## Example Usage

The one-byte header can be used in the future for example in the following ways.

### Message Fragmentation

We found that some WebSocket implementations (e.g. [AWS API Gateway](https://github.com/open-telemetry/opamp-spec/issues/60#issuecomment-1252659494)) limit the message size to 128KB. The only way to overcome this limitation is to perform message fragmentation and reassembly in OpAMP itself. This can be done by using one bit in the header to indicate whether the message is the last fragment.

### Support Other Compression Algorithms

WebSocket has built-in compression. What compression is used depends on the WebSocket implementation and realistically only "deflate" compression implementations are available. There are more modern compression algorithms (e.g. zstd), but it is impossible to use in OpAMP since most known WebSocket implementations simply don't support them.

The one-byte header can easily allow supporting these other compression algorithms. We can use one or or more of the header bits to indicate the compression algorithm used.

Note: this sort of extension can be also done via HTTP header negotiation. However, not all WebSocket implementations allow custom HTTP headers (browsers don't).

## Is This a Breaking Change?

It is, but we can handle it gracefully for a period of time. Here is how.

It is impossible for a valid Protobuf message to start with a zero byte (someone needs to check whether this is true). This makes possible to introduce the header in a way that preserves compatibility with old spec implementations. Implementations need to check the first byte, if it is zero you are dealing with a new message format, if non-zero you are dealing with old message format. 

This detection can only stay temporarily, while zero is the only valid value for the header. So, perhaps we keep it around for a couple months while we are in Beta to give existing implementations time to update and then we deprecate and remove the detection before we declare Stable. This removal will be necessary so that in the future non-zero header values can be used.

## Why One Byte?

Typically we will need one bit per new way of serialization. It is unlikely that we will need more than 8 new indicators. However, even if we do, we can use one of the bits indicate that one-byte header is followed by another header that contains additional information about serialization. 

Alternatively, instead of fixed one-byte header we can use a varint-encoded uint64 header. Values from 0 to 127 would use only one byte (which is likely all we need), but it will be more future proof since it will be possible to use up to 64 bits in the header.

**Comment by tigrannajaryan** [comment]
@andykellr @PeterF778 it would be great to have your thoughts on this.

**Comment by andykellr** [comment]
Quick question: Can we use an HTTP header when the web socket connection is opened? Wouldn't all messages sent during a websocket connection be consistent? If the OpAMP version of the client changes, I think this would involve a reconnect.

**Comment by tigrannajaryan** [comment]
> Quick question: Can we use an HTTP header when the web socket connection is opened? 

Yes, provided that the WebSocket library allows custom headers. Javascript in browser for example doesn't so I don't want to rely on this too much.

>Wouldn't all messages sent during a websocket connection be consistent? If the OpAMP version of the client changes, I think this would involve a reconnect.

Not necessarily. For example to implement message fragmentation and reassembly you need at least one bit per WebSocket message. It can't be done using just HTTP headers.

**Comment by tigrannajaryan** [comment]
We need a resolution on this before going to Stable (and resolution can also be that we don't want it).

**Comment by tigrannajaryan** [comment]
The more I think about this the more attractive it is to me. I have a feeling that if we don't do this we are cornering ourselves into a place where evolving OpAMP will be more difficult. This feature is an escape hatch that we will be able to use. We may end up never needing it but we may regret if we don't. The cost of adding this is small:
- Add the description to the spec: not difficult.
- Size increase on the wire: trivial - 1 byte per message is negligible.
- Implementation complexity: easy.

Is there something that I am overlooking that is more complicated?
