### ISSUE TITLE
Vote for protocol name

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opamp-spec#14]
An objection was raised that perhaps the protocol name is not very good because OpAMP already means something else and will difficult to websearch for: https://github.com/open-telemetry/opamp-spec/issues/3

I am going to post a few different names below, one comment per name. Please vote with +1 (thumbs-up) on the comment for the one(s) that you like most. I am going to include the current name - vote for it if you don't want the name to change.

I am not going to post options which were suggested but which are roughly as bad websearch pollution-wise as the current one.

**Comment by tigrannajaryan** [comment]
OpAMP - the current name, Open Agent Management Protocol

**Comment by tigrannajaryan** [comment]
OAMP - a different abbreviation of Open Agent Management Protocol.

**Comment by tigrannajaryan** [comment]
OpACP - Open Agent Control Protocol

**Comment by tigrannajaryan** [comment]
OSAMP - Open Standard Agent Management Protocol

**Comment by tigrannajaryan** [comment]
OpenACP - Open Agent Control Protocol

**Comment by jmacd** [comment]
Many of these will be confusing with https://github.com/OpenAMP/open-amp

Is this protocol something that we could use to manage an OTel SDK? Is it limited to agents? If I want to ship new sampling policies to clients. I know you're thinking of this as greater than telemetry, but why not something like OpenTelemetry Management Protocol = OTMP?

**Comment by tigrannajaryan** [comment]
> Is this protocol something that we could use to manage an OTel SDK? Is it limited to agents?

Discussed in workgroup, captured here: https://github.com/open-telemetry/opamp-spec/issues/16
Not clear yet, maybe we can.


> but why not something like OpenTelemetry Management Protocol = OTMP?

I want to avoid using OpenTelemetry in the name. It is not Otel-specific, it can/should work for other agents and I want to signal the intent in the name. Besides that is only one-letter difference from OTLP, which can be a source of typos and  confusion.

**Comment by jmacd** [comment]
OpAMP is starting to sound pretty good. 😁 
Sorry I haven't been more helpful.

**Comment by tigrannajaryan** [comment]
> Sorry I haven't been more helpful.

You were, by raising the issue :-)

**Comment by tigrannajaryan** [comment]
I see 7 upvotes on jmacd's comment but it is not clear to me what the upvotes are about. If it is an upvote for the name OTMP then I posted above why I think it has its downsides, I think we should avoid it. If the upvote is for something else please add a comment to explain what you support.

**Comment by mtwo** [comment]
We took a vote during the call to confirm, and the results were

OpAMP: 11
OTMP: 6
OpenRAMP: 5

**OpAMP wins**

**Comment by tigrannajaryan** [comment]
Closing, the voting is closed. The Workgroup considered the impact of noisy websearch of OpAMP name and concluded that it is not a deal breaker.
