### ISSUE TITLE
Feature: Add attribute to Agent Capabilities for mechanism of sending Agent Description

### ISSUE THREAD

**Issue by kailash-bhanushali** [open-telemetry/opamp-spec#142]
There is a requirement where we need Agent Description each time, as I understand opamp-spec is trying to optimize by not sending an Agent Description each time if there is no change. 

Proposed Solution:
So, I would like to propose a solution where we can add in the Agent capabilities which can send Agent Description each time if it is required by the Server.

`enum AgentCapabilities{`
`// ...`
`// Introduced ``Reporting agent description always`` trigger true/false - by default to keep it false`
 `ReportAgentDescriptionAlways = 0x00002000;`
`}`

**Comment by kailash-bhanushali** [comment]
@tigrannajaryan

**Comment by tigrannajaryan** [comment]
The OpAMP server is supposed to track the state per agent (based on instance uid) and in that state the server can keep the agent capabilities. What is the use case where this is impossible?

**Comment by kailash-bhanushali** [comment]
read previous similar issue, so not to be considered for now
