### ISSUE TITLE
Split specification into one page per main section

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opamp-spec#145]
Might it make sense to break the single spec file into a directory with one file/page per spec section (maybe the FAQ and the "Future possibilites" can stay in the top-level README)? I'm asking the following question in the context of the following request:

- https://github.com/open-telemetry/opentelemetry.io/issues/2795

That is, _before_ we publish the spec to the OTel website for the first time, it might be good to consider its structure.

Possible sample structure:

```
/specification
|- README.md
|- communication-model.md
|- operation.md
...
```

/cc @svrnm @cartermp @tigrannajaryan

**Comment by tigrannajaryan** [comment]
@chalin The one doc for the spec worked well so far for the workgroup. We also have one doc for OTLP and typically protocol RFCs also are one large doc. I suggest we keep it as is. Splitting would also require lots of link rewritting, I am not sure it is worth it.

**Comment by chalin** [comment]
👍
