### ISSUE TITLE
Declare stability per capability or for all spec?

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opamp-spec#146]
We discussed that we want to wait for some OpAMP implementations to complete before we declare the spec stable, so that there is time to learn from the implementations and adjust the spec if needed. However the implementations that are in progress don't utilize all OpAMP capabilities, so we can't expect to learn much about these areas.

Should we declare stability of the spec for the capabilities that we know are relatively well-tested and move the other capabilities to a separate section and mark as "Beta" addition to the spec for now?

The spec sections and capabilities I am less confident about and which I think are not used in any implementations so far are:
- [Connection Settings Management](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#connection-settings-management)
- [Packages](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#packages) and [PackageStatuses Message](https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#packagestatuses-message)

We can probably mark these sections as `[Beta]` and the rest of the sections can be declared `Stable`.

@open-telemetry/opamp-spec-approvers what do you think?

**Comment by andykellr** [comment]
I think that makes sense. BindPlane does use Packages and PackageStatuses for agent upgrade and it was worked well. It does not currently use ConnectionSettings.

**Comment by tigrannajaryan** [comment]
> I think that makes sense. BindPlane does use Packages and PackageStatuses for agent upgrade and it was worked well. It does not currently use ConnectionSettings.

@andykellr are there any other capabilities that BindPlane does not use? Do you utilize everything except Connection Settings?

**Comment by andykellr** [comment]
> > I think that makes sense. BindPlane does use Packages and PackageStatuses for agent upgrade and it was worked well. It does not currently use ConnectionSettings.
> 
> @andykellr are there any other capabilities that BindPlane does not use? Do you utilize everything except Connection Settings?

ConnectionSettings and AgentIdentification are not currently used by BindPlane.

**Comment by tigrannajaryan** [comment]
Discussed in workgroup meeting today and decided that it is reasonable to declare only portions of the spec stable and keep less-tested parts as beta. I will work on figuring out the exact labeling mechanism.

**Comment by tigrannajaryan** [comment]
Done in https://github.com/open-telemetry/opamp-spec/pull/147
