### ISSUE TITLE
Clarify OpAMP communication pattern assumptions

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opamp-spec#17]
It may be helpful or necessary to articulate some of the basic aspects of OpAMP's communication _patterns_.
- Is the protocol synchronous or asynchronous?
- Can either party originate requests?
- Are there any generalized behaviors for communication error cases? 
  - What happens if a request is sent but the websocket is closed before a response is received?
  - What happens if a request is sent but no response is received?
  - What happens if a request is sent multiple (many) times without apparent regard for the result?

Probably some of these questions are obvious, implicit in the nuances, or currently undefined. However, as a reader of the spec, it would be helpful to establish any broad rules or assumptions.

**Comment by tigrannajaryan** [comment]
All good questions. I agree these need to be clarified.
