### ISSUE TITLE
OpAMP Agent heartbeats

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opamp-spec#183]
Currently, if an agent is functioning successfully and without any changes to its health or component status, no messages will be sent after initial handshakes. For websockets, because no messages are sent from the agent to the server, after a certain period most of these connections will idle and be shut down causing a broken socket. I propose that we add support for an heartbeat interval as part of the specification. I have already implemented this capability [in the opamp-bridge](https://github.com/open-telemetry/opentelemetry-operator/blob/main/cmd/operator-opamp-bridge/agent/agent.go#L247-L267) where a user is able to configure a heartbeat interval to periodically set the agent's health message. HTTP theoretically gets around this with its polling interval.

This heartbeat implementation is important for the bridge where many of the events in Kubernetes happen asynchronously. The bridge is not informed directly therefore must poll state to send this message. The collector's opamp extension, however, watches for some changes but is currently not busy. For the extension, the collector will idle after sometime and prevent the server from being able to send any more messages to the extension. 

I think a heartbeat interval could be optional, however, it must be communicated as part of the initial AgentToServer message. This would allow the server to know when to mark the agent as unhealthy.

### Open Questions
* Should this functionality only exist for the socket transport?
  * I believe it would be valuable for this to exist regardless of the transport and that the HTTP poll interval could be deprecated in favor of this. This would allow the server to make decisions about the liveness of the agent regardless of the transport
* What should the default interval be? 30s?
* Should the heartbeat interval be negotiable from the server?

I'm happy to write the spec change for this issue, but would love everyone's thoughts here.

**Comment by JaredTan95** [comment]
I think it is reasonable for the agent to actively report a healthy heartbeat, this helps opamp server keep the information up to date.

**Comment by jaronoff97** [comment]
I think the main difference is that my proposal relates to heartbeats as a means of solving #28, allowing clients to automatically report health on an interval. A goal of this is definitely to keep the connection alive, but it also means that the client has a responsibility to reports its health on an interval. I can understand closing this issue in favor of that though...

**Comment by haoqixu** [comment]
A crashed or misbehaving client may cause connection/goroutine leaks in the OpAMP server (open-telemetry/opamp-go#271). A heartbeat mechanism can help the server find out unresponsive peers and also defend against intermediaries (LB, proxy, network equipment) which may time out and terminate idle connections (#28).

**Comment by haoqixu** [comment]
According to the specification, `AgentToServer.health` may be omitted if nothing changed since last AgentToServer message. I think an empty status report is enough for the heartbeats.

**Comment by gdfast** [comment]
I also wanted to give a big +1 to this. The regular status reports from the opamp-bridge have been really useful in
* providing a regular update on status
* acting as a heartbeat
* making sure the opamp agent checks in (especially if it's connecting over HTTP) so we can send any `ServerToAgent` message it needs

I agree with @BinaryFissionGames that for the sake of the OpAMP protocol, this behavior should be transport agnostic (i.e. should work for both HTTP and Websockets given both are valid transport protocols for OpAMP).

**Comment by jaronoff97** [comment]
@tpaschalis I have the PR up [here](https://github.com/open-telemetry/opamp-spec/pull/190) if you can take a look!
