### ISSUE TITLE
PackageStatus message should define a downloading state and include additional metadata

### ISSUE THREAD

**Issue by michel-laterman** [open-telemetry/opamp-spec#204]
[PackageStatus messages](https://opentelemetry.io/docs/specs/opamp/#packagestatus-message) should include an optional `DOWNLOADING` status that may be used by a client to signal that it is downloading the package.
Additionally we allow for an optional metadata attribute (`map[string]string`) to allow additional details related to the state to be included, such as a message, download_rate, download_percent, etc.
metadata should also be optional for the existing states (`INSTALLED`, `INSTALLING`, `INSTALL_FAILED`) and may include relevant information.

This will allow users to determine if the install is taking a long time due to a network issue instead of only having the `INSTALLING` state appear.

**Comment by tigrannajaryan** [comment]
I think `DOWNLOADING` makes sense.

>Additionally we allow for an optional metadata attribute (map[string]string) to allow additional details related to the state to be included, such as a message, download_rate, download_percent, etc.

I would like to understand this part better. Is there a reason we keep it an arbitrary open map of attributes instead of standardizing?

**Comment by michel-laterman** [comment]
My thought is that a generic map will make it easier for a client to add information about any stage of managing package lifecycles, not just downloading.
This information may be useful to end users but not required for the protocol itself
