### ISSUE TITLE
Consider a new name

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opamp-spec#3]
The word "opamp" is commonly used to refer to an operational amplifier, a basic electrical component. This fact already makes it difficult to websearch for this project. I wonder if any other names have been considered?

**Comment by austinlparker** [comment]
+1, would suggest something more descriptive like 'OpenTelemetry Management Protocol' (OTMP) to align with OTLP; Also, relatively low search results for this term means we should be able to ensure that it's highly ranked.

**Comment by tigrannajaryan** [comment]
I kind of like the pun in the name :-) and these days no matter what name we choose there is likely going to be something that matches it.

Anyway, not strongly attached to it. If there is a good, catchy other name we can use that. We should probably avoid using "OpenTelemetry" in the name, to signal the intent that this is usable by any other data collection agent.

Maybe we can name OPAM (OPen Agent Management) or OAMP (hard to pronounce).

**Comment by tigrannajaryan** [comment]
Some other names which are not very polluted in websearch:
OpACP  - Open Agent Control Protocol.
OSAMP - Open Standard Agent Management Protocol.

I can't think of any good names which are not abbreviations.

**Comment by tigrannajaryan** [comment]
@open-telemetry/opamp-spec-approvers any thoughts on this?

**Comment by pmm-sumo** [comment]
I think both "OpACP" and "OSAMP" sound good. Just to throw few more ideas, we could also use a recursive name pattern and do something along following (and just select "x"):

- "xOAMP is Open Agent Management Protocol" 
- "xRAMP is Remote Agent Management Protocol"

**Comment by djaglowski** [comment]
Of the above, I like OAMP the best.

**Comment by pmm-sumo** [comment]
> OpenAMP

There's https://github.com/OpenAMP/open-amp

**Comment by Aneurysm9** [comment]
I like OpenRAMP, or maybe Open Network Remote Agent Management Protocol (ONRAMP) if you really want to lean into the backronym.

I don't think any of the proposed names are objectionable, though, so I'm good with whatever is chosen.

**Comment by tigrannajaryan** [comment]
Seems like a vote is unavoidable. :-) Let me set that up.

**Comment by tigrannajaryan** [comment]
> I like OpenRAMP, or maybe Open Network Remote Agent Management Protocol (ONRAMP) if you really want to lean into the backronym.

Good names, but both seem to be polluted on websearch, so I don't think it is useful to replace the current one with any of these.

**Comment by tigrannajaryan** [comment]
> OpenAMA (Open Agent Management Authority)

"Authority" does not seem to reflect the intent, so I think we should skip this.

> OpenACP (Open Agent Control Protocol)

SGMT and also fairly unique in websearch.

**Comment by tigrannajaryan** [comment]
OK, everyone please vote here https://github.com/open-telemetry/opamp-spec/issues/14

**Comment by tigrannajaryan** [comment]
Voting finished, see https://github.com/open-telemetry/opamp-spec/issues/14#issuecomment-970591632
