### ISSUE TITLE
Agent instance_uid format

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opamp-spec#40]
Specification says that agent's [instance_uid is a string](https://github.com/open-telemetry/opamp-spec#instance_uid), which is recommended to follow [ULID](https://github.com/ulid/spec)

Should we be more strict about the data format and specify it's a 128-bit value (encoded as 16 bytes) rather than string?

Rationale: for servers it might be slightly more efficient to track agents using 128-bits value rather than strings

**Comment by tigrannajaryan** [comment]
I like this. We can change it to be `bytes` in the proto and specify that it MUST be exactly 16 bytes so that we cast to [16]byte in Go implementation and be able to use it as a map key.

**Comment by tigrannajaryan** [comment]
Just discovered one downside.

The spec currently says:
>service.instance.id attribute SHOULD be set to Agent's instance_uid that is used in the OpAMP messages.

This is fine for strings but not with bytes. Although OTLP allows byte attributes [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions#service) says that `service.instance.id` must be a string.

This means we can use `instance_uid` as is for `service.instance.id`, we will to encode it somehow (e.g. hex encode). While it is doable it creates an additional (small) complication and possibility of mistakes and confusion.

I am on on the fence as to move forward with the proposed change or keep it is as a string. The win in efficiency is very small and likely negligible in the overall operation of the server.

**Comment by tigrannajaryan** [comment]
I did quick benchmarking of the id lookup in Go to see if it makes a difference:

```go
type Agent struct {
	instance      string
	data          []byte
	age           int
	someotherdata float64
	somemap       map[string]string
}

func BenchmarkStringMapCreate(b *testing.B) {
	entropy := ulid.Monotonic(rand.New(rand.NewSource(99)), 0)
	var ids []string
	for j := 0; j < 1000000; j++ {
		id := ulid.MustNew(ulid.Timestamp(time.Now()), entropy).String()
		ids = append(ids, id)
	}

	a := &Agent{}
	b.ResetTimer()
	m := map[string]*Agent{}
	for i := 0; i < b.N; i++ {
		for _, id := range ids {
			m[id] = a
		}
	}
}

func BenchmarkStringMapLookup(b *testing.B) {
	m := map[string]*Agent{}
	entropy := ulid.Monotonic(rand.New(rand.NewSource(99)), 0)
	searchid := make([]string, 1000)
	for j := 0; j < 1000000; j++ {
		id := ulid.MustNew(ulid.Timestamp(time.Now()), entropy).String()
		m[id] = &Agent{}
		searchid[j%len(searchid)] = id
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		for _, id := range searchid {
			if _, ok := m[id]; !ok {
				b.Fatal("cannot find")
			}
		}
	}
}

type ID struct {
	lo, hi uint64
}

func BenchmarkUint128MapCreate(b *testing.B) {
	entropy := ulid.Monotonic(rand.New(rand.NewSource(99)), 0)
	var ids []ID
	for j := 0; j < 1000000; j++ {
		ulidid := ulid.MustNew(ulid.Timestamp(time.Now()), entropy)
		bin, err := ulidid.MarshalBinary()
		if err != nil {
			b.Fatal(err)
		}
		id := ID{
			lo: binary.LittleEndian.Uint64(bin[0:8]),
			hi: binary.LittleEndian.Uint64(bin[8:16]),
		}
		ids = append(ids, id)
	}

	a := &Agent{}
	b.ResetTimer()
	m := map[ID]*Agent{}
	for i := 0; i < b.N; i++ {
		for _, id := range ids {
			m[id] = a
		}
	}
}

func BenchmarkUint128MapLookup(b *testing.B) {

	m := map[ID]*Agent{}
	entropy := ulid.Monotonic(rand.New(rand.NewSource(99)), 0)
	searchid := make([]ID, 1000)
	for j := 0; j < 1000000; j++ {
		ulidid := ulid.MustNew(ulid.Timestamp(time.Now()), entropy)
		bin, err := ulidid.MarshalBinary()
		if err != nil {
			b.Fatal(err)
		}
		id := ID{
			lo: binary.LittleEndian.Uint64(bin[0:8]),
			hi: binary.LittleEndian.Uint64(bin[8:16]),
		}

		m[id] = &Agent{}
		searchid[j%len(searchid)] = id
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		for _, id := range searchid {
			if _, ok := m[id]; !ok {
				b.Fatal("cannot find")
			}
		}
	}
}
```

Results:
```
BenchmarkStringMapCreate-8            12          89486282 ns/op
BenchmarkStringMapLookup-8         42909             27671 ns/op
BenchmarkUint128MapCreate-8            9         123236361 ns/op
BenchmarkUint128MapLookup-8        35666             34583 ns/op
```

So the uint128 version is actually slower for whatever reason in Go. The results may be different in other languages (and for other operations with instanceids) but at least Go is important for us and it doesn't benefit from it. 
(One obvious benefits of 128bit version will be the saved memory, which I did not measure).

Given the above benchmark I don't see much point in the change. Whether it is 28ns or 35ns per lookup doesn't really matter, it is going to be insignificant in the grand scheme of the protocol operation.

@pmm-sumo thoughts?

**Comment by tigrannajaryan** [comment]
@pmm-sumo please let me know if you have any other thoughts on this. As it stands now I am inclined towards closing the issue as "won't do".

**Comment by pmm-sumo** [comment]
Thank you @tigrannajaryan for researching this. I agree that at this stage it actually might add complexity for no benefit. 

My original concern (and it could be far-fetched) was about environments with a massive number of tracked agents (which might be especially true when SDK's are also concerned). E.g. when OpAMP is used for managing configuration of mobile applications, perhaps through implementation different than opamp-go, using some sort of persistence underneath. Even then, managing such high volume of agents would probably require heavy use of attributes for classification and having byte-array (or uin128) vs string for identification will be negligible in the end.

Taking all things granted, I am inclining myself towards "won't do" too.

Closing this issue then
