### ISSUE TITLE
OpAMP over plain HTTP transport

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opamp-spec#50]
Certain applications may not need the OpAMP's capabilities enabled by WebSocket (ability to push configs from server without Agent's polling) and may prefer to implement a simpler HTTP transport. This is likely the case for short-lived Agents such as for example the ones running in AWS lambda. The HTTP transport is likely simpler to implement on the Server (easier to manage connections) and also removes an additional dependency (a WebSocket library) from the client.

We are also considering implementing OpAMP in OpenTelemetry SDKs, which can result in significantly larger number of OpAMP Agents connecting to the Server, so the Server has to handle a larger number of persistent WebSocket connections, which may pose more burden than necessary for use cases where there are no benefits from having a persistent connection (e.g. the above mentioned short-lived use case).

Would it be useful to define a plain HTTP transport for OpAMP? It is fairly simple to modify the spec to allow it, with AgentToServer/ServerToAgent messages exchanged via HTTP POST Body.

It is also not very complicated to support both WebSocket and plain HTTP on the same Server and if we want to make it seamless from Agent's perspective we may need to add an indicator of the desired transport in the initial connection attempt made by the Agent, so that the Server knows whether to upgrade to WebSocket or just reply in plain HTTP.

**Comment by carlosalberto** [comment]
I cannot speak much about the Collector case, but for SDKs using HTTP instead of websockets is definitely a good thing.

**Comment by pmm-sumo** [comment]
I think it would be good to have such option, especially since it fits the communication model. Less dependencies for SDK's is a good thing too

**Comment by tigrannajaryan** [comment]
Update: I quickly put some code together and it took about 100 lines to support plain HTTP in our server implementation: https://github.com/open-telemetry/opamp-go/compare/main...tigrannajaryan:plain-http-transport

The client-side plain HTTP implementation will require more work and the differences will be more substantial, but I feel good that a single server can simultaneously support both WebSocket and plain HTTP OpAMP connections on a single port with little extra complexity over the WebSocket-only implementation.

**Comment by yurishkuro** [comment]
I may be missing it, but where is OpAMP defined? I only see Go reference implementation repos.
