### ISSUE TITLE
Agent registration process

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opamp-spec#56]
Currently, OpAMP Client can practically identify itself using two means:
* `instance_uid` field, included in AgentToServer message
* via HTTP authentication fields (using either Basic Auth or Bearer) - if it is using unique credentials

The UID generation is a concern of the agent, which might limit some use cases where certain formats of UID can be used to identify different groups of agents and as such should be provided by server, also ensuring that two agent instances always use different ID's.

For HTTP authentication, there are different use-cases and sometimes a single set of credentials can be used for a larger group of clients. However, it might be preferred to have an initial, installation-only auth token that is used only to identify the type of the agent and handle the registration after which the agent is provided with a unique token that will be used for any further communication. The unique identifier of the agent can be embedded into such token.

Perhaps there's a room to provide support for agent registration procedure, in which a registration-only token is used to get the agent-unique token that will be persisted and used for future communication?

**Comment by mtwo** [comment]
Following up from the weekly call, we should discuss this next session once @pmm-sumo is back. We'd like to understand more about the scenarios that require the unique ID to be provided by the server.

**Comment by tigrannajaryan** [comment]
Discussed in Workgroup meeting. We can add ability for the Server to command the Agent to use a different UID. We can also make UUID optional in the first message from the Agent. The combination of these 2 features allows to:
- Agent to request the Server to assign it a UUID on first connect.
- Server to detect duplicate UUIDs and order Agents to use a different UUID.

**Comment by pmm-sumo** [comment]
I promised to prepare a PR with proposal of the spec update, got a bit delayed but should have it this week
