### ISSUE TITLE
Description of "Operation: Status Reporting by agent" uses outdated field body

### ISSUE THREAD

**Issue by anuraggujral** [open-telemetry/opamp-spec#71]
In the StatusReporting Operation , it is mentioned that the status report is sent as an AgentToServer message, where the body field is set to StatusReport message. I thought the whole AgentToServer message will go as body and not just StatusReport. Filing this issue to correct existing documentation.

**Comment by pmm-sumo** [comment]
Thanks for reporting this @anuraggujral - the fix has been just merged
