### ISSUE TITLE
Move messages in StatusReport to AgentToServer message

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opamp-spec#84]
It is not clear why we have StatusReport, which contains 4 fields, instead of putting the fields directly in AgentToServer.

Can we move the fields to AgentToServer and eliminate StatusReport message?

**Comment by tigrannajaryan** [comment]
Here is what the change can look like: https://github.com/open-telemetry/opamp-go/pull/83

@andykellr @pmm-sumo what do you think?

**Comment by andykellr** [comment]
I like this change.
