### ISSUE TITLE
Clarify how top-level and sub-packages can coexist

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opamp-spec#99]
Packages messages allow both multiple top-level packages and multiple sub-packages.
Presumably sub-packages belong to a particular top-level package, however there is no
way to know this currently.

Do we need to clarify this? Do we need to limit to one top-level package? Do we need a way
to indicate which top-level package the sub-package belongs to?

**Comment by tigrannajaryan** [comment]
@andykellr @pmm-sumo I wonder if you are aware of any use-cases where there are multiple top-level packages, possibly with one or more top-level packages each having sub-packages?
Without knowing the use-cases I find it hard to make the spec clearer and have proper guidance about how to use the PackagesAvailable message.

**Comment by andykellr** [comment]
As I mentioned in the sig meeting, I think the agent/server will need to agree on the specifics of updating packages and can use naming conventions such as a prefix to identify package hierarchy.

**Comment by tigrannajaryan** [comment]
I agree with "agent/server will need to agree on the specifics". Closing, I believe nothing needs to be done here.
